/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.violet.UI;

import AppPackage.AnimationClass;
import java.awt.Image;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.web.WebView;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JScrollPane;

/**
 *
 * @author Admin
 */
public class CuaSoGioiThieuJDialog extends javax.swing.JDialog {

    JFXPanel fxPanel;
    WebView wv;
    JFrame frame;
    AnimationClass ac = new AnimationClass();
    public CuaSoGioiThieuJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadicon();
        slideshow();
        //loadYoutube("http://www.google.com/");
        loadYoutube("https://www.youtube.com/watch_popup?v=9GbLTTGsLyc");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        left = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        sous = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left.setBackground(new java.awt.Color(255, 255, 255));
        left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tittle.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        tittle.setForeground(new java.awt.Color(255, 255, 255));
        tittle.setText("Khách Sạn VIOLET");
        tittle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tittleMouseClicked(evt);
            }
        });
        left.add(tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 190, -1, -1));

        sous.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sous.setForeground(new java.awt.Color(255, 255, 255));
        sous.setText("---------------------------------------------");
        left.add(sous, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));
        left.add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));
        left.add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 500, 500));
        left.add(img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 500, 500));

        container.add(left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        container.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 500, 500));

        getContentPane().add(container, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tittleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tittleMouseClicked
        //loadYoutube("http://www.google.com/");
        //loadYoutube("https://www.youtube.com/watch_popup?v=9GbLTTGsLyc");
    }//GEN-LAST:event_tittleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuaSoGioiThieuJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuaSoGioiThieuJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuaSoGioiThieuJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuaSoGioiThieuJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CuaSoGioiThieuJDialog dialog = new CuaSoGioiThieuJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel left;
    private javax.swing.JLabel sous;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables

    private void loadicon(){
        img1.setIcon(read("src\\com\\violet\\icon\\0001.jpg", 500, 500));
        img2.setIcon(read("src\\com\\violet\\icon\\0002.jpg", 500, 500));
        img3.setIcon(read("src\\com\\violet\\icon\\0003.jpg", 500, 500));
    }
    
    private ImageIcon read(String fileName,int x,int y){       
        ImageIcon image = new ImageIcon(fileName);
        Image im = image.getImage();               
        //return new ImageIcon(path.getAbsolutePath());
        return new ImageIcon(im.getScaledInstance(x, y, im.SCALE_SMOOTH));
    }
    
    public void slideshow(){
        new Thread(new Runnable() {
            @Override
            public void run() {
                int nb = 0;
                try{
                    while(true){
                        switch(nb){
                            case 0:
                                Thread.sleep(3000);
                                ac.jLabelXLeft(0, -500, 12, 10, img1);
                                ac.jLabelXLeft(500, 0, 12, 10, img2);
                                ac.jLabelXLeft(1000, 500, 12, 10, img3);
                                nb++;
                            case 1:
                                Thread.sleep(3000);
                                ac.jLabelXLeft(-500, -1000, 12, 10, img1);
                                ac.jLabelXLeft(0, -500, 12, 10, img2);
                                ac.jLabelXLeft(500, 0, 12, 10, img3);
                                nb++;
                            case 2:
                                Thread.sleep(3000);
                                ac.jLabelXRight(-1000, -500, 12, 10, img1);
                                ac.jLabelXRight(-500, 0, 12, 10, img2);
                                ac.jLabelXRight(0, 500, 12, 10, img3);
                                nb++;
                            case 3:
                                Thread.sleep(3000);
                                ac.jLabelXRight(-500, 0, 12, 10, img1);
                                ac.jLabelXRight(0, 500, 12, 10, img2);
                                ac.jLabelXRight(0, 1000, 12, 10, img3);
                                nb=0;
                        }
                    }
                }catch(Exception e){
                    
                }
            }
        }).start();
    }
    private void loadYoutube(String link){       
        jDesktopPane1.removeAll();
        try {
            fxPanel = new JFXPanel();
            com.sun.javafx.application.PlatformImpl.runLater(new Runnable() {
                @Override
                public void run() {
                    wv = new WebView();
                    wv.getEngine().load(link);
                    fxPanel.setScene(new Scene(wv, 500, 500));
                    frame = new JFrame("Google");
                    frame.add(new JScrollPane(fxPanel));
                    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    //frame.setVisible(true);
                    frame.pack();
                    jDesktopPane1.add(fxPanel).setVisible(true);
                    jDesktopPane1.validate();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }      
    }
}
