/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.violet.UI;

import com.violet.DAO.NhanVienDAO;
import com.violet.Entity.NhanVien;
import com.violet.Help.Auth;
import com.violet.Help.MsgBox;
import com.violet.Help.XImage;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.net.URL;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.Timer;
import net.glxn.qrgen.QRCode;
import net.glxn.qrgen.image.ImageType;

/**
 *
 * @author Admin
 */
public class CuaSoDangNhapJDialog extends javax.swing.JDialog {

    /**
     * Creates new form CuaSoDangNhap
     */
    public CuaSoDangNhapJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new RoundedPanel(50,new Color(255,255,255));
        lblanh = new javax.swing.JLabel();
        lblTaiKhoan = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        lblMatKhau = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        lblQuenPass = new javax.swing.JLabel();
        btnDangNhap = new com.violet.UI.Button();
        btnQuetMa = new com.violet.UI.Button();
        btnThoat = new com.violet.UI.Button();
        lblQR = new javax.swing.JLabel();
        lblQRCode = new javax.swing.JLabel();
        txtQR = new javax.swing.JTextField();
        btnFaceid = new com.violet.UI.Button();
        btnQr = new com.violet.UI.Button();
        btnOTP = new com.violet.UI.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBackground.setOpaque(false);

        lblanh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 10, new java.awt.Color(0, 0, 0)));

        lblTaiKhoan.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblTaiKhoan.setText("Tài Khoản:");
        lblTaiKhoan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txtTaiKhoan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTaiKhoan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        lblMatKhau.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblMatKhau.setText("Mật Khẩu:");
        lblMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txtPass.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        lblQuenPass.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblQuenPass.setText("Quên Mật Khẩu ?");
        lblQuenPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuenPassMouseClicked(evt);
            }
        });

        btnDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/violet/icon/login.png"))); // NOI18N
        btnDangNhap.setText("Đăng Nhập");
        btnDangNhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        btnQuetMa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/violet/icon/DangKi.png"))); // NOI18N
        btnQuetMa.setText("Quét Mã");
        btnQuetMa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnQuetMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuetMaActionPerformed(evt);
            }
        });

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/violet/icon/Thoat.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        lblQR.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblQR.setText("Không phải robot ?");
        lblQR.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        lblQRCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtQR.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtQR.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        btnFaceid.setText("FACE ID");
        btnFaceid.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnFaceid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFaceidActionPerformed(evt);
            }
        });

        btnQr.setText("QR");
        btnQr.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnQr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQrActionPerformed(evt);
            }
        });

        btnOTP.setText("OTP");
        btnOTP.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOTPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblanh, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMatKhau)
                            .addComponent(lblTaiKhoan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPass, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTaiKhoan, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(btnOTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQRCode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(lblQR)
                        .addGap(18, 18, 18)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addComponent(lblQuenPass, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtQR)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnFaceid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(btnQuetMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnQr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)))
                .addContainerGap())
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaiKhoan)
                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatKhau)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQR)
                    .addComponent(txtQR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblQuenPass)
                .addGap(22, 22, 22)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuetMa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFaceid, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btnQr, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQRCode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(lblanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pnlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        dangNhap();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        thoat();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void lblQuenPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenPassMouseClicked
        // TODO add your handling code here:
        new QuenMatKhauJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_lblQuenPassMouseClicked

    private void btnQuetMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuetMaActionPerformed
        try {
            Random generator = new Random();
            value = generator.nextInt((9999-1000)+ 1)+1000;
            ByteArrayOutputStream out = QRCode.from(String.valueOf(value)).to(ImageType.PNG).stream();
            
            String f_name = String.valueOf(value);
            String Path_name = "logos\\" ;
            
            System.out.println(f_name);
            File fl = new File("logos\\"+f_name+".PNG");
            if(fl.exists()){
                return;
            }
            
            FileOutputStream fout = new FileOutputStream(new File(Path_name +(f_name + ".PNG")));
            fout.write(out.toByteArray());
            fout.flush();
            
            //ImageIcon icon = new ImageIcon("logos\\"+ f_name + ".png");
            
            lblQRCode.setIcon(XImage.read2(f_name+".png",200,200));
            
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnQuetMaActionPerformed

    private void btnFaceidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFaceidActionPerformed
        // TODO add your handling code here:
        new NhanDienDangNhap(null, true).setVisible(true);
    }//GEN-LAST:event_btnFaceidActionPerformed

    private void btnQrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQrActionPerformed
        // TODO add your handling code here:
        new QuetQRCodeJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_btnQrActionPerformed

    private void btnOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOTPActionPerformed
        // TODO add your handling code here:
        try {
            MsgBox.alert(null, "Hãy mở APP REST SMS Gateway và nhấn Start !");
            String link = MsgBox.prompt(null, "Nhập vào đường dẫn hiện ra trên APP !");
            Random generator = new Random();
            value = generator.nextInt((9999-1000)+ 1)+1000;
            String str = "Mã xác nhận của bạn là : "+ String.valueOf(value) + "";
            String str2 = str.replaceAll("\\s", "+");
            String contact = MsgBox.prompt(null, "Nhập vào SDT !");
            URL url = new URL(link+"v1/sms/send/?phone="+contact+"&message="+str2+"");
            InputStream i = null;
            MsgBox.alert(null, "Message Sent Successfully");
            
            try{
                i = url.openStream();
            }catch(Exception e){
                e.printStackTrace();
            }
            
            if(i != null){
                
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnOTPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuaSoDangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuaSoDangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuaSoDangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuaSoDangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CuaSoDangNhapJDialog dialog = new CuaSoDangNhapJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.violet.UI.Button btnDangNhap;
    private com.violet.UI.Button btnFaceid;
    private com.violet.UI.Button btnOTP;
    private com.violet.UI.Button btnQr;
    private com.violet.UI.Button btnQuetMa;
    private com.violet.UI.Button btnThoat;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblQR;
    private javax.swing.JLabel lblQRCode;
    private javax.swing.JLabel lblQuenPass;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JLabel lblanh;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtQR;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;

        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }

        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
        }

        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
            //graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
        }
    }
    private void init(){
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0.0f,0.0f,0.0f,0.0f));
        lblanh.setIcon(XImage.read2("DangNhapBackground.jpg", 503, 464));
        checkTK();
    }
    
    int value = 0;
    NhanVienDAO dao = new NhanVienDAO();
    
    private void dangNhap(){
        String manv = txtTaiKhoan.getText();
        String matkhau = new String(txtPass.getPassword());
        NhanVien nhanVien = dao.selectById(manv);
        if(nhanVien == null){
            MsgBox.alert(this,"Sai tên đăng nhập!");
        }else if(!matkhau.equals(nhanVien.getMatKhau())){
            MsgBox.alert(this,"Sai mật khẩu!");
        }else if(!txtQR.getText().equals(String.valueOf(value))){
            MsgBox.alert(this, "Sai mã xác nhận QR !");
        }else{
            Auth.user = nhanVien;
            this.dispose();
        }
    }
    private void thoat(){
        if(MsgBox.confirm(this, "Bạn muốn kết thúc ứng dụng ?")){
            System.exit(0);
        }
    }
    private void checkTK(){
        new Timer(1, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(Auth.isLogin()){
                    setDuLieu();
                }
            }
        }).start();
    }
    private void setDuLieu(){
        txtTaiKhoan.setText(Auth.user.getMaNV());
        txtPass.setText(Auth.user.getMatKhau());
    }
}
